### ISSUE TITLE
How to make app work

### ISSUE THREAD

**Issue by poolboy135** [vakho10/Native-Messaging#3]
Hi, I'm fairly new to programming but I'm interested to see how this native messaging program works. I've opened the project in an IDE but some parts of the Java code don't really make sense.

**Comment by vakho10** [comment]
@poolboy135 Hi, tell me which part is ambiguous and I'll try to answer you. You are right, this project itself is old and there might be something off.

**Comment by poolboy135** [comment]
@vakho10 It's mainly the byte counting in the Java code, but on the whole, I'm just not sure how the native messaging is supposed to work with the browser

**Comment by vakho10** [comment]
@poolboy135 The idea is simple. You have native app on your system and the extension installed in the browser (for example on Chrome). The webpage calls extension, which itself calls the native application (java application) install on your system. That's it.

**Comment by poolboy135** [comment]
@vakho10 So where exactly are the files for the extension? Is it in app or app_native?

**Comment by vakho10** [comment]
@poolboy135 Read the README.md file. I've described the project structure. The extension files are in App folder.
